version: "3.8"

services:
  db:
    container_name: hackathon-db
    build:
      context: .
      dockerfile: db/Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 3306:3306
    env_file:
      - db/.env_mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./db/init
        target: /docker-entrypoint-initdb.d
  
  backend:
    container_name: hackathon-backend
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/x86_64
    tty: true
    ports:
      - 8000:8000
    env_file:
      - .env

volumes:
  mysql-data:
    name: mysql-volume