# version: "3.8"

# services:
#   db:
#     container_name: db
#     build:
#       context: .
#       dockerfile: Dockerfile
#     platform: linux/x86_64
#     tty: true
#     ports:
#       - 3306:3306
#     env_file:
#       - ./.env_mysql
#     volumes:
#       - type: volume
#         source: mysql-data
#         target: /var/lib/mysql
#       - type: bind
#         source: ./init
#         target: /docker-entrypoint-initdb.d

# volumes:
#   mysql-data:
#     name: mysql-volume

version: "3.9"
services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: hackathon-db
    ports:
      - "3308:3308"
    expose:
      - 3308
    command: --port 3308
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      TZ: "Asia/Tokyo"
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  mysql-data:
    name: mysql-volume