version: "3.9"
services:
  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: hackathon-db
    ports:
      - "3308:3308"
    expose:
      - 3308
    command: --port 3308
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      LANG: ja_JP.UTF-8
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d

volumes:
  mysql-data:
    name: mysql-volume